inherit_from: .rubocop_todo.yml
Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Style/AsciiComments:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - app/services/message_apis/helpers.rb
AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'