# version: '2.4'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile.development
    args:
      RUBY_VERSION: '3.3.5'
      PG_MAJOR: '15'
      NODE_MAJOR: '16'
      YARN_VERSION: '1.13.0'
      BUNDLER_VERSION: '2.3.26'
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
    ANYCABLE_DEBUG: ${DEBUG:-0}
    ANYCABLE_RPC_HOST: 0.0.0.0:50051
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - packs:/app/public/packs
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
    - .dockerdev/.bashrc:/root/.bashrc:ro
  environment:
    <<: *env
    REDIS_URL: redis://redis:6379/
    DATABASE_URL: postgres://postgres:password@postgres:5432/chaskiq_dev
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 1
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/bash
    image: chaskiq-runner:local

  rpc:
    <<: *backend
    command: bundle exec anycable

  anycable:
    image: 'anycable/anycable-go:1.0-alpine'
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      ANYCABLE_HOST: 0.0.0.0
      ANYCABLE_HEADERS: cookie,origin
      REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: rpc:50051
      ANYCABLE_DEBUG: ${DEBUG:-0}
    depends_on:
      - redis
      - rpc

  rails:
    <<: *backend
    command: ./bin/dev
    image: chaskiq-rails:local
    ports:
      - '3000:3000'
      - '3001:3001'

  # sidekiq:
  #   <<: *backend
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   image: chaskiq-sidekiq:local

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chaskiq_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chaskiq_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres: null
  redis: null
  bundle: null
  rails_cache: null
  packs: null
