admin:
  manage:
    - all
manager:
  manage:
    - all
agent:
  login_to: conversations
  blocks_access:
  manage:
    - conversations
    - platform
  read:
  write:

program_manager:
  login_to: :conversations
  manage:
    - app
    - app_settings
    - messenger_settings
    - webhooks
    - api_access
    - dashboard
    - campaigns
    - routing_bots
    - help_center
  read:
    - conversations
    - platform
    - reports
    - settings
  write:
admin_only:
  manage:
    - conversations
    - platform_segments
    - users
  read:
    - dashboard
    - campaigns
    - routing_bots
    - help_center
    - reports
    - settings
  write: