admin:
  manage:
    - all
manager:
  manage:
    - all
agent:
  login_to: conversations
  manage:
    - conversations
    - platform
  read:
    - segments
  write:

program_manager:
  login_to: :conversations
  manage:
    - app
    - app_settings
    - app_packages
    - messenger_settings
    - outgoing_webhooks
    - oauth_applications
    - dashboard
    - campaigns
    - routing_bots
    - help_center
  read:
    - conversations
    - platform
    - reports
    - settings
    - segments
  write:
admin_only:
  manage:
    - conversations
    - segments
    - users
  read:
    - dashboard
    - campaigns
    - routing_bots
    - help_center
    - reports
    - settings
    - app_packages
  write:



#    - app
#    - app_settings
#    - app_packages
#    - messenger_settings
#    - outgoing_webhooks
#    - oauth_applications
#    - dashboard
#    - campaigns
#    - routing_bots
#    - help_center
#    - dashboard
#    - campaigns
#    - routing_bots
#    - help_center
#    - reports
#    - settings
#    - assign_rules
#    - quick_replies