#!/usr/bin/env sh

docker build --build-arg APP_ENV=production \
             --build-arg RUBY_VERSION=3.3.5 \
             --build-arg PG_MAJOR=15 \
             --build-arg NODE_MAJOR=16 \
             --build-arg YARN_VERSION=1.13.0 \
             --build-arg BUNDLER_VERSION=2.3.26 \
             -f $DOCKERFILE_PATH \
             -t $IMAGE_NAME \
             .

