#!/usr/bin/env sh

docker build --build-arg RUBY_VERSION=2.6.5 --build-arg PG_MAJOR=11 --build-arg NODE_MAJOR=10 --build-arg YARN_VERSION=1.13.0 --build-arg BUNDLER_VERSION=2.0.2  -f $DOCKERFILE_PATH -t $IMAGE_NAME .