json.extract! campaign, *[:id,
:config_fields, 
:reply_email, 
:html_content,  
:serialized_content,  
:state, 
:app_id, 
:created_at, 
:updated_at, 
].concat(campaign.config_fields.map{|o| o[:name]})
