import {
  AUTH,
  PING,
  CONVERT,
  CONVERSATIONS,
  CONVERSATION,
  INSERT_COMMMENT,
  START_CONVERSATION,
  ARTICLE_SETTINGS,
  ARTICLES,
  SEARCH_ARTICLES,
  ARTICLES_UNCATEGORIZED,
  ARTICLE,
  ARTICLE_COLLECTIONS,
  ARTICLE_COLLECTION,
  ARTICLE_COLLECTION_WITH_SECTIONS,
  APP_PACKAGE_HOOK,
} from './queries';

const GQQueries = {
  AUTH: AUTH,
  PING: PING,
  CONVERT: CONVERT,
  CONVERSATIONS: CONVERSATIONS,
  CONVERSATION: CONVERSATION,
  INSERT_COMMMENT: INSERT_COMMMENT,
  START_CONVERSATION: START_CONVERSATION,
  ARTICLE_SETTINGS: ARTICLE_SETTINGS,
  ARTICLES: ARTICLES,
  SEARCH_ARTICLES: SEARCH_ARTICLES,
  ARTICLES_UNCATEGORIZED: ARTICLES_UNCATEGORIZED,
  ARTICLE: ARTICLE,
  ARTICLE_COLLECTIONS: ARTICLE_COLLECTIONS,
  ARTICLE_COLLECTION: ARTICLE_COLLECTION,
  ARTICLE_COLLECTION_WITH_SECTIONS: ARTICLE_COLLECTION_WITH_SECTIONS,
  APP_PACKAGE_HOOK: APP_PACKAGE_HOOK,
};

// example
// npx babel-node ./app/javascript/src/graphql/entry.mjs APPS
var myArgs = process.argv.slice(2);
console.log(GQQueries[myArgs[0]]);
//console.log(Direction[myArgs[0]])
